const RESPONSE_CODES = {
  API: {
    NOT_FOUND: "API_NOT_FOUND",
    UNEXPECTED_ERROR: "API_UNEXPECTED_ERROR",
    LIMIT_EXCEEDED: "API_LIMIT_EXCEEDED",
    INVALID_QUERY_PARAMS: "API_INVALID_QUERY_PARAMS",
    INVALID_ID_SELECTOR: "API_INVALID_ID_SELECTOR",
    ID_SELECTOR_NOT_FOUND: "API_ID_SELECTOR_NOT_FOUND",
  },
  FILE: {
    TOO_LARGE: "FILE_TOO_LARGE",
    UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
    INVALID_TYPE: "FILE_INVALID_TYPE",
  },
  AUTH: {
    TOKEN_MISSING: "AUTH_TOKEN_MISSING",
    TOKEN_INVALID: "AUTH_TOKEN_INVALID",
    UNAUTHORIZED: "AUTH_UNAUTHORIZED",
    FORBIDDEN: "AUTH_FORBIDDEN",
    VALIDATION_ERROR: "AUTH_VALIDATION_ERROR",
    EMAIL_ALREADY_REGISTERED: "AUTH_EMAIL_ALREADY_REGISTERED",
    USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
    INCORRECT_PASSWORD: "AUTH_INCORRECT_PASSWORD",
    RESET_TOKEN_INVALID: "AUTH_RESET_TOKEN_INVALID",
  },
  USER: {
    VALIDATION_ERROR: "USER_VALIDATION_ERROR",
  },
  THREAD: {
    VALIDATION_ERROR: "THREAD_VALIDATION_ERROR",
  },
  LIKE: {
    ALREADY_EXISTS: "LIKE_ALREADY_EXISTS",
  },
  REPLY: {
    VALIDATION_ERROR: "REPLY_VALIDATION_ERROR",
  },
};

export default RESPONSE_CODES;
